name: Deploy Frontend Only

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      # 레포지토리 소스를 체크아웃
      - name: Use repository source
        uses: actions/checkout@v3

      # Node.js 런타임 설정
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # 프로젝트에서 사용하는 Node.js 버전

      # node_modules 폴더 캐싱
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          # 캐싱할 경로를 front 폴더 내부로 제한
          path: Front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('Front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Dependencies 설치 (front 폴더 내부에서 실행)
      - name: Install dependencies
        working-directory: Front
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      # PUBLIC_URL 설정
      - name: Set PUBLIC_URL
        working-directory: Front
        run: |
          PUBLIC_URL=$(echo $GITHUB_REPOSITORY | sed -r 's/^.+\/(.+)$/\/\1\//')
          echo PUBLIC_URL=$PUBLIC_URL > .env

      # 빌드 수행
      - name: Build
        working-directory: Front
        run: |
          npm run build
          cp ./build/index.html ./build/404.html
        env:
          CI: false

      # 빌드된 파일을 gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Front/build
